services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql

    php1:
        build: .
        volumes:
            - ./Serveur1:/var/www/html
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        depends_on:
            - db
        command: /bin/sh -c "composer install && npm install && npm run build && php artisan migrate && php-fpm"

    php2:
        build: .
        volumes:
            - ./Serveur2:/var/www/html
        environment:
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        depends_on:
            - db
        command: /bin/sh -c "composer install && npm install && npm run build && php-fpm"

    nginx1:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./Serveur1/Config.conf:/etc/nginx/conf.d/default.conf
            - ./Serveur1:/var/www/html
        depends_on:
            - php1

    nginx2:
        image: nginx:alpine
        ports:
            - "8081:80"
        volumes:
            - ./Serveur2/Config.conf:/etc/nginx/conf.d/default.conf
            - ./Serveur2:/var/www/html
        depends_on:
            - php2

volumes:
    mysql_data:
