version: "3"
services:
    php:
        image: php:8.2-fpm
        ports:
            - 8181:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: myUser
            WORDPRESS_DB_PASSWORD: myPassword
            WORDPRESS_DB_NAME: myDb
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: myUser
            MYSQL_PASSWORD: myPassword
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
